### ISSUE TITLE
G_Gametype is mixed up

### ISSUE THREAD

**Issue by br33zy59** [ceular/devotion#38]
Current version g_gametype seems to have some confusion. After a bit of testing it looks like the modes are currently:
0 - FFA
1 - Duel
2 - Invalid gametype
3 - TDM
4 - CTF
5 - Elimination (Callvote: One-flag CTF) 
6 - CTF Elimination (Callvote: Overload)
7 - Last Man Standing (Callvote: Harvester)
8 - Invalid Gametype (Callvote: Elimination)

Clan Arena seems to be missing, mode 2 is missing. Modes 5+ are a different description in the callvote to the actual mode. Something to do with a Team Arena conflicts?

**Comment by ceular** [comment]
I did take a look at this before and the fix should be fairly easy, I have been really lazy lately
Thanks for opening an issue about this

**Comment by alcachofass** [comment]
I believe https://github.com/ceular/devotion/pull/43 fixes this issue. It is purely cosmetic in the console.
