### ISSUE TITLE
Map rotation issues with g_gametype 1

### ISSUE THREAD

**Issue by rawbert0** [ceular/devotion#42]
Tested map rotations with g_gametype 1 with several scenarios and was unable to get any kind of map rotations to work. With g_gametype 0, the standard rotation works as expected.

set m1 "map map1; set nextmap vstr m2"
set m2 "map map2; set nextmap vstr m1"
vstr m1

Is there something I'm missing?

**Comment by ceular** [comment]
Yes, the comma in the first line that you edited out and setting a timelimit

**Comment by rawbert0** [comment]
Sorry, that was a typo as this is not the real script. However, the timelimit is set in the main config (outside of the map script). Have tested with putting in a timelimit and setting the g_gametype per item, and have tested calling an external maplist config as well as putting the rotation inside the main server config.

**Comment by ceular** [comment]
NEVERMIND the pattern should be this
```
set d1 "nextmap q3dm1; vstr d2"
set d2 "nextmap q3dm2; vstr d3"
set d3 "nextmap q3dm3; vstr d4"
set d4 "nextmap q3dm4; vstr d5"
set d5 "nextmap q3dm5; vstr d6"
set d6 "nextmap q3dm6; vstr d1"
```

**Comment by rawbert0** [comment]
Thanks, will test that right now.

**Comment by ceular** [comment]
i just tested it myself and that behavior happens even in VQ3 for whatever reason

**Comment by rawbert0** [comment]
Yeah, just tested this too. Thanks.
